---
deployment:
  tasks:
    - export DEPLOYPATH=/home/denspark/denspark/
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R utils $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp config.py $DEPLOYPATH
    - /bin/cp extensions.py $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH