"""add is_read and new columns to messages

Revision ID: 40e6823587e9
Revises: 
Create Date: 2026-04-25 16:21:19.993179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40e6823587e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cloudinary_id', sa.String(length=200), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_id')
        batch_op.drop_column('cloudinary_url')
        batch_op.drop_column('featured')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('sender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_read')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('sender_name')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
